### ISSUE TITLE
Possibly unwanted result when shuffling activities.

### ISSUE THREAD

**Issue by Sam-Belliveau** [stuysu/stuyactivities.org#83]
I was just reviewing code when I stumbled upon
```js
	const organizations = data?.organizations?.filter(org => org.url !== "stuysu") || [];
	shuffleArray(organizations, seed);
	if (organizations?.length !== (data?.organizations || []).length) {
		organizations.unshift(data?.organizations?.find(org => org.url === "stuysu"));
	}
```
in [Catalog.js](https://github.com/stuysu/stuyactivities.org/blob/master/src/pages/Catalog.js).

I believe in the event that an organizations url is equal to `stuysu`, it may be accidentally left unshuffled.

**Comment by Sam-Belliveau** [comment]
There are two possible ways I could think of to fix this, the first one would be to change it to,

```js 
    const organizations = data?.organizations || [];
    shuffleArray(organizations, seed);
```

if that doesn't work for yall, theres also this code which might help solve the problem a little.

```js
    const special = ["stuyvesantrobotics", "stuysu"];
    const organizations = data?.organizations?.filter(org => !special.includes(org.url)) || [];
    shuffleArray(organizations, seed);
    for(var club in special) {
        if(data?.organizations?.some(org => org.url === club)) {
            organizations.unshift(data?.organizations?.find(org => org.url === club));
        }
    }
```

**Comment by abir-taheer** [comment]
This isn't a bug. The intention was for the stuysu organization to always show up first in the catalog.
